name: dart_unitz
description: A simple and expandable unit conversion library. Quickly and easily convert between units and apply math operations on any unit.
version: 0.0.5
repository: https://github.com/mj12358/dart-unitz

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  # decimal: ^2.3.2
  meta: ^1.9.1

dev_dependencies:
  dart_lintz: ^1.1.0
  test: ^1.24.3
